# Relax or disable some strict RuboCop rules for this project.

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'

# Disable or relax metrics that are too strict for small puzzle scripts
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Disable documentation/frozen string literal requirements for quick scripts
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Allow longer lines in this repo
Layout/LineLength:
  Max: 120